/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_okcoin_vault_jni_qtum_QtumNativeInvoke */

#ifndef _Included_com_okcoin_vault_jni_qtum_QtumNativeInvoke
#define _Included_com_okcoin_vault_jni_qtum_QtumNativeInvoke
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_okcoin_vault_jni_qtum_QtumNativeInvoke
 * Method:    execute
 * Signature: (Ljava/lang/String;)[B
 */
JNIEXPORT jobjectArray JNICALL Java_com_okcoin_vault_jni_qtum_QtumNativeInvoke_execute
  (JNIEnv *, jclass, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
